name = "shift/gem"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'shift/gem'"

[repository]
user = "shift"
project = "gem"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[packages]
test = "test"  

[config]